builds:
  - binary: pylai
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

universal_binaries:
  - replace: true

brews:
  - name: pylai
    homepage: "https://github.com/arlomcwalter/pylai"
    description: "Simple cli totp manager and authenticator"
    folder: Formula
    tap:
      owner: arlomcwalter
      name: homebrew-tap
    commit_author:
      name: arlomcwalter
      email: mcwalterarlo@gmail.com

checksum:
  name_template: 'checksums.txt'